src/admin_m/urls.py
from django.contrib import admin
from django.urls import path
from admin_m import views
from django.contrib.auth import login ,logout

urlpatterns = [
    path('',view=views.menu,name='customers:menu_list'),
    path('signin/',view=views.signin,name='login_page'),
    path('signout/',view=views.signout,name='logout_page'),
    path('signup/',view=views.signup,name='signup_page'),
    path('welcome/',view=views.welcome,name='welcome_page'),
    path('menu/',view=views.menu,name='menu_list'),
    path('createmenu/',view=views.createmenu,name='createmenu_page'),
    path('delete/<int:pk>',view=views.delete,name='delete_page'),
    path('edit/<int:pk>',view=views.edit,name='edit_page'),
    path('orders',view=views.orders,name='orders'),
    path('orders/<int:pk>',view=views.order_detail,name='order_detail'),
    path('orders/<int:pk>/status',view=views.order_status_update,name='update_order_status'),
    
    

]

src/customers/urls.py
from django.contrib import admin
from django.urls import path
from customers import views
from django.contrib.auth import login ,logout

app_name = 'customers'

urlpatterns = [
    path('index/',view=views.index,name='index_page'),
    path('signup/',view=views.signup,name='signup_page'),
    path('signin/',view=views.signin,name='login_page'),
    path('',view=views.menu,name='menu_list'),
    path('detail/<int:pk>', view=views.food_detail, name='food_detail'),
    path('cart/',view=views.cart,name='cart_list'),
    path('clear-cart',view=views.clear_cart,name='clear_items'),
    path('remove-item/<int:pk>',view=views.remove_item,name='remove_item'),
    path('checkout/',view=views.checkout,name='checkout'),
    path('receipt/',view=views.receipt,name='receipt'),
    path('track-order/',view=views.track_order,name='track_order')
]

src/shaws_food_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('createmenu/', include('admin_m.urls')),
    path('',include('customers.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/customers/models.py
from django.db import models

# Create your models here.

src/customers/forms.py
from django import forms



class CheckoutForm(forms.Form):
    email = forms.EmailField(max_length=25)
    first_name = forms.CharField(max_length=25)
    last_name = forms.CharField(max_length=25)
    address = forms.CharField(max_length=256)
    delivery_type = forms.CharField(max_length=25)
    card_name = forms.CharField(max_length=50)
    card_number = forms.CharField(max_length=25)
    cvv_number = forms.CharField(max_length=25)
    expiration_date = forms.DateField()

src/customers/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login , logout
from django.contrib.auth.forms import UserCreationForm ,AuthenticationForm
from django.contrib.auth.models import User

from .shopping_cart import ShoppingCart
from admin_m import forms as admin_forms
from admin_m.models import Meals, Order, OrderItem
from . import forms




def index(request):
    return render (request, template_name='customers/index.html')


def signup(request):
    if request.user.is_authenticated:
        return redirect('customers:menu_list')
    if request.method == 'POST':
        # form = UserCreationForm(request.POST)
        
        form = admin_forms.SignupForm(request.POST)
        if form.is_valid():
            
            email = form.cleaned_data.get('email')
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            password = form.cleaned_data.get('password')

            #cerate user
            user = User.objects.create_user(username=email, 
                                            email=email,
                                            password=password, 
                                            first_name=first_name, 
                                            last_name=last_name)

            
            login(request, user)
            return redirect('customer:menu_list')
        else:
            return render(request, 'customers/signup.html', {'form': form})
    else:
        form = admin_forms.SignupForm()
        return render(request, 'customers/signup.html', {'form': form})

def signin(request):
    if request.user.is_authenticated:
        return render(request, 'customers/menulist.html')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('customers:menu_list')
        else:
            form = AuthenticationForm(request.POST)
            return render(request, 'customers/signin.html', {'form': form})
    else:
        form = AuthenticationForm()
        return render(request, 'customers/signin.html', {'form': form})


def menu(request):
    search=request.GET.get('search')
    if search:
        foods=Meals.objects.filter(name__startswith=search)
    
        

    else:
        foods = Meals.objects.all()


    return render(request,template_name='customers/menulist.html' , context={
                                                        'menu': foods})



def food_detail(request, pk):

    if request.method == 'POST':
        qty = request.POST.get('quantity')
        name = request.POST.get('name')
        price = request.POST.get('price')

        cart = ShoppingCart(session=request.session)
        cart.add_item(item_id=pk, quantity=qty, name= name , price= price )

        return redirect('customers:menu_list')
    else:
        food = Meals.objects.get(pk=pk)
        return render(request, template_name='customers/food_detail.html', context={
            'food': food
        })

def cart (request):
    purchased = request.session.get('cart_items')
    cart = ShoppingCart(session=request.session)
    total = cart.sum_total()
    return render (request, template_name='customers/cart_list.html', context={
        'cart' : purchased,
        'total': total
    })

def clear_cart (request):
    cart = ShoppingCart(session=request.session)
    cart.clear_items()
    return redirect('customers:menu_list')

def remove_item (request,pk):
    cart = ShoppingCart(session=request.session)
    cart.remove_item(pk)
    return redirect('customers:cart_list')


def checkout(request):
    form = forms.CheckoutForm()
    cart = request.session.get("cart_items")
    if request.method == 'POST':
        form = forms.CheckoutForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            order_items = [{
                "meal_id": item["item_id"],
                "quantity": item["qty"],
                "subtotal": item["sub_total"]
            } for item in cart]
            cart_object = ShoppingCart(session=request.session)
            total = cart_object.sum_total()

            order = Order.objects.create(
                email = data.get('email'),
                first_name = data.get('first_name'),
                last_name = data.get('last_name'),
                address = data.get('address'),
                delivery_type = data.get('delivery_type'),
                card_name = data.get('card_name'),
                card_number = data.get('card_number'),
                cvv_number = data.get('cvv_number'),
                expiration_date = data.get('expiration_date'),
                total = total
                )
            
            for item in order_items:
                order_items_created = OrderItem.objects.create(
                    meal_id=item.get('meal_id'),
                    subtotal=item.get('subtotal'),
                    quantity=item.get('quantity')
                )
                order.order_item.add(order_items_created) #i am addding the reference of OrderItem to the order model
            
            order.save()
            print(order_items)
            cart_object.clear_items()
            return redirect("customers:receipt")
    return render(request, template_name='customers/checkout.html', context={'form':form})


def receipt(request):
    return render(request, template_name='customers/receipt_page.html')


def track_order(request):
    context = {}
    if request.GET.get('tracking_number'):
        tracking_number = request.GET.get('tracking_number')
        order = Order.objects.filter(id=tracking_number).first()
        context['order'] = order
        context['tracking_number'] = tracking_number
        print(order.__dict__)
    return render(request, template_name='customers/track_order.html', context=context)
    

src/customers/templates/customers/base.html
 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>{% block title %}Home{% endblock title %}</title>
</head>
<body>
    <div class="bkimg">
        <div class="container">
            <div class="navbar navbar-expand-lg navbar-light bg-light">

                {% if request.user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'logout_page' %}">LOGOUT</a>
                {% else %}
                
                <a class="nav-item nav-link" href="{% url 'customers:signup_page' %}">SIGNUP</a>
                <a class="nav-item nav-link" href="{% url 'customers:login_page' %}">LOGIN</a>
                
                {% endif %}

                <a class="nav-item nav-link" href="{% url 'customers:track_order' %}"> Track Order</a>
                <a class="nav-item nav-link" href="{% url 'customers:cart_list' %}"> Cart: {{ request.session.cart_items|length }}</a>
            </div>
        </div>
    </div>
    <div class="content">
        {% block content %}  <h1> Welcome {{user}}</h1> {% endblock content %}
    </div>
    
</body>

</html>

src/customers/templates/customers/cart_list.html
{% extends 'customers/base.html'%}


{% block content %}
<h3> YOUR ORDER {{ user }} </h3>

<div class="container">
    <div class="row">
        <div class="col col-sm-4">
            <table class= "table table-bordered">
                <th>
                    <tr>
                        <td><h3>Name</h3></td>
                        <td><h3>Quantity</h3></td>
                        <td><h3>Price</h3></td>
                        <td><h3>Sub total</h3></td>
                        <td><h3></h3></td>

                    </tr>
                </th>
                <tbody>
                    {% for item in cart %}
                    <tr>
                        <td>{{item.name}}</td>
                        <td>{{item.qty}}</td>
                        <td>${{item.price}}</td>
                        <td>${{item.sub_total}}</td>
                        <td>
                            <a href="{% url 'customers:remove_item' pk=item.item_id %}"
                             onclick="return confirm('Are you sure you want to remove this item?');">Remove</a>
                             | <a href="{% url 'customers:food_detail' pk=item.item_id %}?update=true">Edit</a>
                            </td>
                        
                    </tr>

                    {% endfor %}
                    <tr>
                        <td></td>
                        <td></td>
                        <td><b>TOTAL</b></td>
                        <td><b>${{total}}</b></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
            <a href="{% url 'customers:clear_items' %}" 
            onclick="return confirm('Are you sure you want to clear the Cart?');">Clear Cart</a>
        </div>

    </div>
    <div class="row">
        <div class="col">
            <a href="{% url 'customers:checkout' %}" class="btn btn-success">Checkout</a>
        </div>
    </div>
</div>

{% endblock %}


{% block title %}
List of Meals
{% endblock %}

src/customers/templates/customers/checkout.html
{% extends "customers/base.html" %}

{% block content %}

<div class="row">
    <div class="col col-sm-10 offset-sm-1 col-lg-4 offset-lg-4 ">
        <form method="post">
            {% csrf_token %}
            <h2>Customer's Delivery Info</h2>
            <div class="form-row">
                <label>Email Address</label>
                <input type="email" name="{{ form.email.name }}" value="{{ form.email.value|default:'' }}" />
                {% if form.email.errors %}
                <span style="color: red;">{{ form.email.errors }} </span>
                {% endif %}
            </div>
        
            <div>
                <label>First Name</label>
                <input type="text" name="{{ form.first_name.name }}" value="{{ form.first_name.value|default:'' }}" />
                {% if form.first_name.errors %}
                <span style="color: red;">{{ form.first_name.errors }} </span>
                {% endif %}
            </div>
        
            <div>
                <label>Last Name</label>
                <input type="text" name="{{ form.last_name.name }}" value="{{ form.last_name.value|default:'' }}" />
                {% if form.last_name.errors %}
                <span style="color: red;">{{ form.last_name.errors }} </span>
                {% endif %}
            </div>

            <div>
                <label>Pickup/Delivery</label>
                <select name="delivery_type" id="delivery_type">
                    <option value="">Select an option</option>
                    <option value="delivery">Delivery</option>
                    <option value="pickup">Pickup</option>
                </select>
                {% if form.delivery_type.errors %}
                <span style="color: red;">{{ form.delivery_type.errors }} </span>
                {% endif %}
            </div>

            
        
            <div>
                <label>Address</label>
                <textarea type="text" name="{{ form.address.name }}" value="{{ form.address.value|default:'' }}" ></textarea>
                {% if form.address.errors %}
                <span style="color: red;">{{ form.address.errors }} </span>
                {% endif %}
            </div>

            <hr>

            <h2>Payment information</h2>

            <div>
                <label>Card Name</label>
                <input type="text" name="{{ form.card_name.name }}" value="{{ form.card_name.value|default:'' }}" />
                {% if form.card_name.errors %}
                <span style="color: red;">{{ form.card_name.errors }} </span>
                {% endif %}
            </div>

            <div>
                <label>Card Number</label>
                <input type="text" name="{{ form.card_number.name }}" value="{{ form.card_number.value|default:'' }}" />
                {% if form.card_number.errors %}
                <span style="color: red;">{{ form.card_number.errors }} </span>
                {% endif %}
            </div>

            <div>
                <label>CVV Number</label>
                <input type="text" name="{{ form.cvv_number.name }}" value="{{ form.cvv_number.value|default:'' }}" />
                {% if form.cvv_number.errors %}
                <span style="color: red;">{{ form.cvv_number.errors }} </span>
                {% endif %}
            </div>

            <div>
                <label>Expiration Date</label>
                <input type="date" name="{{ form.expiration_date.name }}" value="{{ form.expiration_date.value|default:'' }}" />
                {% if form.expiration_date.errors %}
                <span style="color: red;">{{ form.expiration_date.errors }} </span>
                {% endif %}
            </div>

        
            <input type="submit" value="CheckOut" class="btn btn-primary">
        </form>
    </div>
    
</div>

{% endblock content %}

src/customers/templates/customers/food_detail.html
{% extends "customers/base.html" %}

{% block content %}

<div class="row">
    <div class="col col-sm-10 offset-sm-1 col-lg-4 offset-lg-4 ">
        <img src="/media/{{food.image}}" alt="{{food.name}}" style="width: 100%;" />
    </div>
    <div class="col col-sm-10 offset-sm-1 col-lg-4 offset-lg-4 ">
        <h4>{{food.name}}</h4>
        <h5>${{food.price}}</h5>
        <form method="POST">
            {% csrf_token %}
            <label>Quatity</label>
            <input type="number" value="1" name="quantity" />
            <input type="hidden" value="{{food.name}}" name="name">
            <input type="number" value="{{food.price}}" name="price">
            {% if request.GET.update %}
            <button>Update cart</button>
            {% else %}
            <button>Add to cart</button>
            {% endif %}
        </form>
    </div>
</div>

{% endblock content %}

src/customers/templates/customers/index.html
{% extends 'customers/base.html' %}

{% block title %}
    customer registration
{% endblock%}


{% block content %}

<p>Hi </p>
    
{% endblock%}

src/customers/templates/customers/menulist.html
{% extends 'customers/base.html'%}


{% block content %}
<div class="container">
<!-- <h3 class="text-center"> YOUR ORDER {{ user }} </h3> -->

<!-- <nav class="navbar navbar-light bg-light">
    <div class="container">
        <form class="form-inline mx-auto" method="get">
            <input class="form-control mr-sm-2" type="search" placeholder="Search by name" aria-label="Search"
                name="search">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav> -->
<div class="jumbotron bg-light">
    <h1 class="display-4">Hello, {{user}}!</h1>
    <p class="lead">What would you like to eat today?</p>
    <hr class="my-4">
    <p class="mt-2">
        <form class="form-inline justify-content-center" method="get">
            <input class="form-control mr-sm-2 col-6" type="search" placeholder="Search by name" aria-label="Search"
                name="search">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </p>
  </div>
<!-- <form action="" method="get">
    <input type="search" name="search" id="" placeholder="search by name">
    <button type="submit">SEARCH</button>
</form> -->

<!-- <table class="table table-borderless">
    <thead>
        <tr>
            <th scope="col">Image</th>
            <th scope="col">Name</th>
            <th scope="col">Category</th>
            <th scope="col">Calories</th>
            <th scope="col">Price ($)</th>
        </tr>
    </thead>
    <tbody> -->

    <div class="row">
        {% for food in menu %}
        <div class="col col-sm-3">
            <div class="card mb-4" style="">
                <img class="card-img-top" src="/media/{{food.image}}" height="130" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{food.name}}</h5>
                    <p class="card-text">{{food.category}}   {{food.calories}}cal </p>
                    <p class="card-text">
                    <h4>${{food.price}}</h4>
                    </p>
                    <a href="{% url 'customers:food_detail' pk=food.id %}" class="btn btn-primary">Add to cart</a>
                </div>
            </div>

            <!-- 

            
            <td><img src="/media/{{food.image}}" width="60" /> </td>
            <td>{{food.name}}</td>
            <td>{{food.category}}</td>
            <td>{{food.calories}} </td>
            <td>{{food.price}}</td> -->


        </div>
        {% endfor %}
    </div>
<!-- </tbody>
</table> -->
</div>
{% endblock %}


{% block title %}
List of Meals
{% endblock %}

src/customers/templates/customers/receipt_page.html
{% extends 'customers/base.html' %}

{% block content %}
<div class="row">
    <div class="col col-sm-10 offset-sm-1 col-lg-4 offset-lg-4 ">
        your order has been placed. Relax while we deliver it to you.
    </div>
    <div class="col col-sm-10 offset-sm-1 col-lg-4 offset-lg-4 ">
        click <a href="{% url 'customers:menu_list' %}">here</a> to go to the menu listing page
    </div>
</div>
{% endblock %}

src/customers/templates/customers/signin.html
{% extends 'customers/base.html' %}
        
{% block  content %}

<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Sign in" class="btn btn-outline-primary">
</form>

{% endblock %}


{% block tiltle %}
     signin
{% endblock %}
    

src/customers/templates/customers/signup.html
{% extends 'customers/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <!-- {{form.as_p}} -->
    <div class="form-row">
        <label>Email Address</label>
        <input type="email" name="{{ form.email.name }}" value="{{ form.email.value|default:'' }}" />
        {% if form.email.errors %}
        <span style="color: red;">{{ form.email.errors }} </span>
        {% endif %}
    </div>

    <div>
        <label>First Name</label>
        <input type="text" name="{{ form.first_name.name }}" value="{{ form.first_name.value|default:'' }}" />
        {% if form.first_name.errors %}
        <span style="color: red;">{{ form.first_name.errors }} </span>
        {% endif %}
    </div>

    <div>
        <label>Last Name</label>
        <input type="text" name="{{ form.last_name.name }}" value="{{ form.last_name.value|default:'' }}" />
        {% if form.last_name.errors %}
        <span style="color: red;">{{ form.last_name.errors }} </span>
        {% endif %}
    </div>

    <div>
        <label>Password</label>
        <input type="password" name="{{ form.password.name }}" value="{{ form.password.value|default:'' }}" />
        {% if form.password.errors %}
        <span style="color: red;">{{ form.password.errors }} </span>
        {% endif %}
    </div>

    <div class="form-group">
        <label>Confirm Password</label>
        <input type="password" name="{{ form.confirm_password.name }}" class="form-control"
            value="{{ form.confirm_password.value|default:'' }}" />
        {% if form.confirm_password.errors %}
        <span style="color: red;">{{ form.confirm_password.errors }} </span>
        {% endif %}
    </div>

    <input type="submit" value="Sign up" class="btn btn-primary">
</form>
{% endblock %}

{% block title %}
sign up
{% endblock %}

src/customers/templates/customers/track_order.html
{% extends 'customers/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <form method="GET">
                <div class="form-group">
                    <label>Tracking Number</label>
                    <input class="form-control" type="number" name="tracking_number" value="{{ tracking_number|default:'' }}" />
                    {% if errors %}
                    <span style="color: red;">{{ errors }} </span>
                    {% endif %}
                </div>
            
                <input type="submit" value="Track Order" class="btn btn-primary">
            </form>
        </div>
    </div>
    {% if order %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <ul>
                <li>Name: {{order.first_name}}</li>
                <li>Email: {{order.email}}</li>
                <li>Address: {{order.address}}</li>
                <li>Status: {{order.status}}</li>
                <li>Order Items:
                    <ol>
                        {% for item in order.order_item.all %}
                            <li>Name: {{item.meal.name}} Quantity: {{item.quantity}}</li>
                        {% endfor %}
                    </ol>
                </li> 
            </ul>
        </div> 
    </div>
    {% endif %}
</div>
{% endblock %}

{% block title %}
sign up
{% endblock %}